version: '3.8'

services:
  rag_pro:
    build: .
    container_name: rag_pro_app
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./uploaded_files:/app/uploaded_files
      - ./chroma_db:/app/chroma_db
      - ./app/db:/app/app/db
    restart: unless-stopped
